
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import tkinter.font as font
import tkinter as tk

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


#window = Tk()

#window.geometry("1000x600")
#window.configure(bg = "#FFFFFF")
class Entrance_UI(Canvas):
    def __init__(self, parent):
        #super().__init__()
        #self.geometry("1000x600")
        #self.configure(bg = "#FFFFFF")       
        Canvas.__init__(self, parent)
        self.configure(
            #window,
            bg = "#FFFFFF",
            height = 600,
            width = 1000,
            bd = 0,
            relief = "ridge",
            highlightthickness = 0,
        )
        
        self.place(x = 0, y = 0)
        self.entry_image_1 = PhotoImage(
            file=relative_to_assets("entry.png"))
        self.entry_bg_1 = self.create_image(
            712.0,
            330.5,
            image=self.entry_image_1
        )
        self.input = tk.StringVar(self)
        self.entry_1 = Entry(self,
            textvariable = self.input,
            bd=0,
            bg="#C4C4C4",
            highlightthickness=0
        )
        self.myFont = font.Font(family='Helvetica', size=20)
        self.entry_1['font'] = self.myFont
        self.entry_1.place(
            x=552.0,
            y=300.5,
            width=320.0,
            height=58.0
        )
        
        self.button_image_1 = PhotoImage(
            file=relative_to_assets("button.png"))
        self.button_1 = Button(self,
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_1 clicked"),
            relief="flat"
        )
        self.button_1.place(
            x=635.0,
            y=408.0,
            width=154.0,
            height=57.0
        )
        
        self.image_image_1 = PhotoImage(
            file=relative_to_assets("image.png"))
        self.image_1 = self.create_image(
            494.0,
            300.0,
            image=self.image_image_1
        )
        #self.resizable(False, False)
    def get_input(self):
        return self.input
    def get_button(self):
        return self.button_1
#window.mainloop()
#canvas = Entrance_UI(window)
#window.resizable(False, False)
#window.mainloop()
